language: node_js
node_js:
- '0.10'
before_script:
- pwd
- gem install compass
- npm install
- npm install bower
- bower install
- npm install grunt-cli
- rm -rf dist/bower_components
- grunt
deploy:
  provider: s3
  access_key_id: AKIAISJMRUQ4YJVE4AYA
  secret_access_key:
    secure: E1SMwWvV4J2OWS+kQcu/DnCaVR+Jf1wigk+guvlAS9YcqQuaVJNMDiMWJdoHO6tnv3PIY2JtVgxMA4IRpW9F0RDHeJh2k6C5D+szw0x+XRnfbTx57YLw2c1b+IwXKp5Rl7hAzVsvaUZC4NuU6vbwxS+SOKIsICfq6r2VmpS0zoY=
  bucket: lastfm-angular
  local-dir: $TRAVIS_BUILD_DIR/dist
  on:
    repo: keymholio/lastfm-angular
