language: node_js
node_js:
- '0.10'
before_script:
- gem install compass
- npm install
- npm install bower
- npm install grunt-cli
- pip install awscli
- grunt
env:
  global:
  - secure: YEJT4xO66MIgxWoLk9m11hkIS/4FJ60kfiokcTwM3SXbxXYIHe0Rcu5fYTrlUKPZpY42lW9zXtJxnvbGqdbKiXssZavROO+HURUkAMoZiCFPnT9WFb30VvG9x08dYFOXJLOTQ+MVCJQcNoYLbPMDOpDRnVCqp6vpIMKhJyBUm/A=
  - secure: CvJFi0uaIlu0be+ld7oLfD9SfewQ+yZUvTstF2M7zFE+arDVXELB7LWDK6AR5FzHyXrUxLEEoiLweSEHbPjTSiI60GKtHUT93mfHVXm8MznHxqjpE4c0kgkbiZoY2tnv5ACbdtOxURV9y1378DEnH4GuTK/+S9fMFxdwGBHp6Sc=
  - secure: htUNiqSgexD9FSlIM2s+JPqSc2mSdOZqtcssJvOeqRzLeFfPrSIV0QFXqNokhkvHE7/t3KYncw8Bo8z4NhJl7vdrPX2tO1akYYh4Y0QXz4W+YDY1N6n3FwzupPITvsO0XADbNBtGFM6RaLZ0T3sfbNi4++bmvgPVsBxo2zXNG3E=
after_script:
- aws s3 rm s3://lastfm-angular --recursive
- aws s3 sync dist s3://lastfm-angular --acl public-read --cache-control "public, max-age=86400"
